### ISSUE TITLE
组件以application运行时 现在的配置 有问题

### ISSUE THREAD

**Issue by cjztool** [13767004362/ModulePattern#1]
当你的main组件以application形式运行时(你的isAlone=true，然后跑main)，main组件完全没有依赖movie组件 导致 movieListProvider 即使Autowired 也必然为null ....

**Comment by 13767004362** [comment]
> 当你的main组件以application形式运行时(你的isAlone=true，然后跑main)，main组件完全没有依赖movie组件 导致 movieListProvider 即使Autowired 也必然为null ....

main组件是movelist组件和collection组件的容器角色，离开这两个是无法独立运行的。这个案例，只是为了展示如何搭建组件化，展示如何处理app空壳、组件通讯、组件之间页面接入等问题。
